import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Notification} from './components/Notification'
import './globals.css'
import 'react-datepicker/dist/react-datepicker.css'
import {Header} from './components/Header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="p-8 xl:p-24">{children}</div>
        <Notification />
      </body>
    </html>
  )
}
