import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Notification} from '../components/Notification'
import {notFound} from 'next/navigation'
import './globals.css'
import 'react-datepicker/dist/react-datepicker.css'
import {Header} from '../components/Header'

const inter = Inter({subsets: ['latin']})

// Can be imported from a shared config
const locales = ['en', 'es']

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {locale},
}: {
  children: React.ReactNode
  params: {locale: string}
}) {
  if (!locales.includes(locale as any)) notFound()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="p-8 xl:p-24">{children}</div>
        <Notification />
      </body>
    </html>
  )
}
