import {Inter} from 'next/font/google'
import {notFound} from 'next/navigation'
import './globals.css'
import {Notification} from '../components/Notification'
import ThemeToggle from '../components/ThemeToggle'

const inter = Inter({subsets: ['latin']})

// Can be imported from a shared config
const locales = ['en', 'es']

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params: {locale},
}: {
  children: React.ReactNode
  params: {locale: string}
}) {
  if (!locales.includes(locale as any)) notFound()

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} dark:bg-black`}
        suppressHydrationWarning
      >
        <ThemeToggle>{children}</ThemeToggle>
      </body>
      <Notification />
    </html>
  )
}
