import {Inter} from 'next/font/google'
import {notFound} from 'next/navigation'
import './globals.css'
import {Header} from '../components/Header'
import {Notification} from '../components/Notification'

const inter = Inter({subsets: ['latin']})

// Can be imported from a shared config
const locales = ['en', 'es']

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params: {locale},
}: {
  children: React.ReactNode
  params: {locale: string}
}) {
  if (!locales.includes(locale as any)) notFound()

  return (
    <html lang={locale}>
      <body className={`${inter.className}`}>{children}</body>
      <Notification />

    </html>
  )
}
